// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/service/service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	structures "avito/pkg/structures"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSegment is a mock of Segment interface.
type MockSegment struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentMockRecorder
}

// MockSegmentMockRecorder is the mock recorder for MockSegment.
type MockSegmentMockRecorder struct {
	mock *MockSegment
}

// NewMockSegment creates a new mock instance.
func NewMockSegment(ctrl *gomock.Controller) *MockSegment {
	mock := &MockSegment{ctrl: ctrl}
	mock.recorder = &MockSegmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegment) EXPECT() *MockSegmentMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSegment) Create(segment structures.Segment) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", segment)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSegmentMockRecorder) Create(segment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSegment)(nil).Create), segment)
}

// Delete mocks base method.
func (m *MockSegment) Delete(segment structures.Segment) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", segment)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSegmentMockRecorder) Delete(segment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSegment)(nil).Delete), segment)
}

// MockUserSegments is a mock of UserSegments interface.
type MockUserSegments struct {
	ctrl     *gomock.Controller
	recorder *MockUserSegmentsMockRecorder
}

// MockUserSegmentsMockRecorder is the mock recorder for MockUserSegments.
type MockUserSegmentsMockRecorder struct {
	mock *MockUserSegments
}

// NewMockUserSegments creates a new mock instance.
func NewMockUserSegments(ctrl *gomock.Controller) *MockUserSegments {
	mock := &MockUserSegments{ctrl: ctrl}
	mock.recorder = &MockUserSegmentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSegments) EXPECT() *MockUserSegmentsMockRecorder {
	return m.recorder
}

// GetUsersInSegment mocks base method.
func (m *MockUserSegments) GetUsersInSegment(user structures.User) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersInSegment", user)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersInSegment indicates an expected call of GetUsersInSegment.
func (mr *MockUserSegmentsMockRecorder) GetUsersInSegment(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersInSegment", reflect.TypeOf((*MockUserSegments)(nil).GetUsersInSegment), user)
}

// Patch mocks base method.
func (m *MockUserSegments) Patch(userSegments structures.UserSegments) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", userSegments)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockUserSegmentsMockRecorder) Patch(userSegments interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockUserSegments)(nil).Patch), userSegments)
}
