version: "3.9"
services:
  db:
    image: postgres:15
    container_name: avito_db
    ports:
      - 5434:5432
    restart: always
    env_file:
      - .env
    volumes:
      - ./chema/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: .
    container_name: avito_service
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    depends_on:
      - db
#    volumes:
#      - server_data:/app/data

#volumes:
#  db_data:
#  server_data:
