version: "3.9"
services:
  db:
    image: postgres:15
    container_name: avito_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
#    volumes:
#      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: .
    container_name: avito_service
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
#    volumes:
#      - server_data:/app/data

#volumes:
#  db_data:
#  server_data:
