basePath: /api/
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  handler.validCreateSegmentResponse:
    properties:
      slug:
        type: string
    type: object
  handler.validDeleteSegmentResponse:
    properties:
      slug:
        type: string
    type: object
  handler.validGetUserHistoryResponse:
    properties:
      report:
        example: http://localhost:8000/files/reports/user_history_YYYY-MM_0.csv
        type: string
      user_id:
        type: integer
    type: object
  handler.validGetUserSegmentsResponse:
    properties:
      segments:
        items:
          type: string
        type: array
      user_id:
        type: integer
    type: object
  handler.validPatchResponse:
    properties:
      user_id:
        type: integer
    type: object
  structures.Segment:
    properties:
      slug:
        type: string
    required:
    - slug
    type: object
  structures.UserSegments:
    properties:
      segments_to_add:
        items:
          type: string
        type: array
      segments_to_delete:
        items:
          type: string
        type: array
      user_id:
        type: integer
    required:
    - segments_to_add
    - segments_to_delete
    - user_id
    type: object
host: localhost:8000
info:
  contact:
    email: mail@dj.ama1.ru
    name: GADJIIAVOV DJAMAL
    url: https://dj.ama1.ru
  title: Avito Test Assignment
  version: "1.0"
paths:
  /segments/:
    delete:
      consumes:
      - application/json
      operationId: delete-segment
      parameters:
      - description: Slug of segment
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/structures.Segment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.validDeleteSegmentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Delete Segment
      tags:
      - segment
    get:
      description: |-
        You can also use the request body to send data, but not here :)
        p.s. For example, via curl
      operationId: get-user-segments
      parameters:
      - description: User id
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.validGetUserSegmentsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get User Segments
      tags:
      - user-segments
    patch:
      consumes:
      - application/json
      operationId: patch-segment
      parameters:
      - description: Patch data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/structures.UserSegments'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.validPatchResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Patch Segment
      tags:
      - user-segments
    post:
      consumes:
      - application/json
      operationId: create-segment
      parameters:
      - description: Slug of segment
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/structures.Segment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.validCreateSegmentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Create Segment
      tags:
      - segment
  /users/history/:
    get:
      description: |-
        You can also use the request body to send data, but not here :)
        p.s. For example, via curl
      operationId: get-user-history
      parameters:
      - in: query
        name: user_id
        required: true
        type: integer
      - example: YYYY-MM
        in: query
        name: year_month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.validGetUserHistoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get User History
      tags:
      - user
swagger: "2.0"
